build: off

image: Visual Studio 2019

stack: go 1.14

clone_folder: c:\gopath\src\gonum.org\v1\gonum

cache:
  - '%LocalAppData%\go-build'

environment:
  GO111MODULE: 'on'

branches:
  only:
    - master

build_script:
  - go version
  - go get -v -t ./...

test_script:
  - go test ./...
