build: off

clone_folder: c:\gopath\src\gonum.org\v1\gonum

cache:
  - '%LocalAppData%\go-build'

branches:
  only:
    - master

environment:
  matrix:
    - GOROOT: 'c:\go19'
    - GOROOT: 'c:\go110'
    - GOROOT: 'c:\go111'
  GOPATH: c:\gopath
  GOTOOLDIR: '%GOROOT%\pkg\tool\windows_amd64'
  PATH: '%GOPATH%\bin;%GOROOT%\bin;%PATH%'

build_script:
  - "%GOROOT%\\bin\\go version"
  - "%GOROOT%\\bin\\go get -v -t ./..."

test_script:
  - "%GOROOT%\\bin\\go test ./..."
